### ISSUE TITLE
您好 这个可用吗？ README 信息太少啦

### ISSUE THREAD

**Issue by Skyball** [ourcolour/sobookscrawler#1]

**Comment by ourcolour** [comment]
Environment
--
MacOS X and later
Python 3.X  and later
MongoDB4.X  and later
_(Optional) Aliyun ACM_
_(Optional) pan.baidu.com (for e-book fetching)_

Configuration
--
[${PROJ_ROOT}/crawler/configs.py](https://github.com/ourcolour/sobookscrawler/blob/master/crawler/configs.py)

Main Entry
--
python ${PROJ_ROOT}/crawler/main_sobooks.py
